make EscapeCommands less recursive
The expression
    parser.dfLineGroupParser(1000 * "f").toTex()
would previously fail with a
    RuntimeError: maximum recursion depth exceeded ...
due to the recursive nature of the escape method.