work around empty lines in Index,v
Currently deleting the last page from a course can result in the Index,v
to consist of a single empty line. Such an Index,v actually exists and
thus has to be handled gracefully instead of raising an IndexError. Thus
we need to skip lines that are empty.

Full traceback that lead to the investigation:

Traceback (most recent call last):
  File "/usr/local/stow/dokuforge2-2012.07.22.a6bec137f79f71ea2bd556e496151b15b1d6dc68/lib/python2.6/dist-packages/dokuforge/serve_scgi_forkpool.py", line 26, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/pymodules/python2.6/werkzeug/wsgi.py", line 406, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/pymodules/python2.6/werkzeug/wrappers.py", line 245, in <lambda>
    return _patch_wrapper(f, lambda *a: f(*a[:-2]+(cls(a[-2]),))(*a[-2:]))
  File "/usr/local/lib/python2.6/dist-packages/dokuforge/application.py", line 433, in __call__
    return getattr(self, "do_%s" % endpoint)(rs, **args)
  File "/usr/local/lib/python2.6/dist-packages/dokuforge/application.py", line 1132, in do_save
    return self.render_show(rs, aca, c, page, saved=True)
  File "/usr/local/lib/python2.6/dist-packages/dokuforge/application.py", line 1493, in render_show
    blobs=[thecourse.viewblob(i) for i in thecourse.listblobs(thepage)])
  File "/usr/local/lib/python2.6/dist-packages/dokuforge/course.py", line 458, in listblobs
    if int(entries[0]) == number:
IndexError: list index out of range